version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: algebrawl
      POSTGRES_PASSWORD: password
      POSTGRES_DB: algebrawl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
